### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Flash1232** [James137137/ChunkLoader#1]
I am running it on a Spigot 1.10 but it does not seem to keep chunks loaded when I move away.

**Comment by James137137** [comment]
:-( ok. Guess I might have to redo this plugin...

How were you testing it?

**Comment by Unpaid8503** [comment]
Same problem.

```
[00:14:47 WARN]: org.apache.commons.lang.UnhandledException: Plugin ChunkLoader v1.8.0 generated an exception while executing task 19
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at nz.co.lolnet.james137137.mcstats.Metrics.postPlugin(Metrics.java:342)
        at nz.co.lolnet.james137137.mcstats.Metrics.access$400(Metrics.java:57)
        at nz.co.lolnet.james137137.mcstats.Metrics$1.run(Metrics.java:227)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by James137137** [comment]
ok that is easy fix

**Comment by James137137** [comment]
I'm surprised I missed that

**Comment by James137137** [comment]
@ErmanSayin please use http://dev.bukkit.org/bukkit-plugins/chunkloader/files/8-chunk-loader/

the version you have is very old
